# Generated by Django 4.2.10 on 2024-03-21 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0002_gamereview"),
        ("payment", "0002_payment_card_last_four"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="game_name",
        ),
        migrations.AddField(
            model_name="payment",
            name="game",
            field=models.ForeignKey(
                default=155, on_delete=django.db.models.deletion.CASCADE, to="game.game"
            ),
            preserve_default=False,
        ),
    ]
