# Generated by Django 4.2.10 on 2024-02-25 19:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Platform",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name="game",
            name="platform",
        ),
        migrations.AddField(
            model_name="game",
            name="platforms",
            field=models.ManyToManyField(to="game.platform"),
        ),
    ]
