# Generated by Django 4.2.10 on 2024-02-25 20:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0002_platform_remove_game_platform_game_platforms"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="image",
            field=models.ImageField(upload_to=""),
        ),
    ]
