# Generated by Django 4.2.10 on 2024-02-25 20:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0003_alter_game_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="image",
            field=models.ImageField(upload_to="images/"),
        ),
    ]
